// priority: 999

const METALS = {
    iron: {
        ore: 'minecraft:iron_ore',
        clump: 'kubejs:iron_clump',
        cluster: 'kubejs:iron_cluster',
        dirty_dust: 'kubejs:iron_dust_dirty',
        crushed: 'create:crushed_iron_ore',
        nugget: 'minecraft:iron_nugget',
        dust: 'immersiveengineering:dust_iron',
        ingot: 'minecraft:iron_ingot',
        block: 'minecraft:iron_block',
        slab: '',
        plate: '',
        rod: '',
        sheet: '',
        slab_sheet: '',
        half_slab_sheet: '',
        melting_temp: 1400
    },
    gold: {
        ore: 'minecraft:gold_ore',
        clump: 'kubejs:gold_clump',
        cluster: 'kubejs:gold_cluster',
        dirty_dust: 'kubejs:gold_dust_dirty',
        crushed: 'create:crushed_gold_ore',
        nugget: 'minecraft:gold_nugget',
        dust: 'immersiveengineering:dust_gold',
        ingot: 'minecraft:gold_ingot',
        block: 'minecraft:gold_block',
        slab: '',
        plate: '',
        rod: '',
        sheet: '',
        slab_sheet: '',
        half_slab_sheet: '',
        melting_temp: 1063
    },
    copper: {
        ore: 'create:copper_ore',
        clump: 'kubejs:copper_clump',
        cluster: 'kubejs:copper_cluster',
        dirty_dust: 'kubejs:copper_dust_dirty',
        crushed: 'create:crushed_copper_ore',
        nugget: 'create:copper_nugget',
        dust: 'immersiveengineering:dust_copper',
        ingot: 'create:copper_ingot',
        block: 'create:copper_block',
        slab: '',
        plate: '',
        rod: '',
        sheet: '',
        slab_sheet: '',
        half_slab_sheet: '',
        melting_temp: 1084
    },
    zinc: {
        ore: 'create:zinc_ore',
        clump: 'kubejs:zinc_clump',
        cluster: 'kubejs:zinc_cluster',
        dirty_dust: 'kubejs:zinc_dust_dirty',
        crushed: 'create:crushed_zinc_ore',
        nugget: 'create:zinc_nugget',
        dust: 'kubejs:zinc_dust',
        ingot: 'create:zinc_ingot',
        block: 'create:zinc_block',
        slab: '',
        plate: '',
        rod: '',
        sheet: '',
        slab_sheet: '',
        half_slab_sheet: '',
        melting_temp: 420
    },
    silver: {
        ore: 'immersiveengineering:ore_silver',
        clump: 'kubejs:silver_clump',
        cluster: 'kubejs:silver_cluster',
        dirty_dust: 'kubejs:silver_dust_dirty',
        crushed: 'create:crushed_silver_ore',
        nugget: 'immersiveengineering:nugget_silver',
        dust: 'immersiveengineering:dust_silver',
        ingot: 'immersiveengineering:ingot_silver',
        block: 'immersiveengineering:storage_silver',
        slab: '',
        plate: '',
        rod: '',
        sheet: '',
        slab_sheet: '',
        half_slab_sheet: '',
        melting_temp: 961
    },
    lead: {
        ore: 'immersiveengineering:ore_lead',
        clump: 'kubejs:lead_clump',
        cluster: 'kubejs:lead_cluster',
        dirty_dust: 'kubejs:lead_dust_dirty',
        crushed: 'create:crushed_lead_ore',
        nugget: 'immersiveengineering:nugget_lead',
        dust: 'immersiveengineering:dust_lead',
        ingot: 'immersiveengineering:ingot_lead',
        block: 'immersiveengineering:storage_lead',
        slab: '',
        plate: '',
        rod: '',
        sheet: '',
        slab_sheet: '',
        half_slab_sheet: '',
        melting_temp: 328
    },
    aluminum: {
        ore: 'immersiveengineering:ore_aluminum',
        clump: 'kubejs:aluminum_clump',
        cluster: 'kubejs:aluminum_cluster',
        dirty_dust: 'kubejs:aluminum_dust_dirty',
        crushed: 'create:crushed_aluminum_ore',
        nugget: 'immersiveengineering:nugget_aluminum',
        dust: 'immersiveengineering:dust_aluminum',
        ingot: 'immersiveengineering:ingot_aluminum',
        block: 'immersiveengineering:storage_aluminum',
        slab: '',
        plate: '',
        rod: '',
        sheet: '',
        slab_sheet: '',
        half_slab_sheet: '',
        melting_temp: 660
    },
    uranium: {
        ore: 'immersiveengineering:ore_uranium',
        clump: 'kubejs:uranium_clump',
        cluster: 'kubejs:uranium_cluster',
        dirty_dust: 'kubejs:uranium_dust_dirty',
        crushed: 'create:crushed_uranium_ore',
        nugget: 'immersiveengineering:nugget_uranium',
        dust: 'immersiveengineering:dust_uranium',
        ingot: 'immersiveengineering:ingot_uranium',
        block: 'immersiveengineering:storage_uranium',
        slab: '',
        plate: '',
        rod: '',
        sheet: '',
        slab_sheet: '',
        half_slab_sheet: '',
        melting_temp: 1132
    },
    nickel: {
        ore: 'immersiveengineering:ore_nickel',
        clump: 'kubejs:nickel_clump',
        cluster: 'kubejs:nickel_cluster',
        dirty_dust: 'kubejs:nickel_dust_dirty',
        crushed: 'create:crushed_nickel_ore',
        nugget: 'immersiveengineering:nugget_nickel',
        dust: 'immersiveengineering:dust_nickel',
        ingot: 'immersiveengineering:ingot_nickel',
        block: 'immersiveengineering:storage_nickel',
        slab: '',
        plate: '',
        rod: '',
        sheet: '',
        slab_sheet: '',
        half_slab_sheet: '',
        melting_temp: 1453
    },
    tin: {
        ore: 'kubejs:tin_ore',
        clump: 'kubejs:tin_clump',
        cluster: 'kubejs:tin_cluster',
        dirty_dust: 'kubejs:tin_dust_dirty',
        crushed: 'create:crushed_tin_ore',
        nugget: 'kubejs:tin_nugget',
        dust: 'kubejs:tin_dust',
        ingot: 'kubejs:tin_ingot',
        block: 'kubejs:tin_block',
        slab: '',
        plate: '',
        rod: '',
        sheet: '',
        slab_sheet: '',
        half_slab_sheet: '',
        melting_temp: 232
    },
    titanium: {
        ore: '',
        clump: '',
        cluster: '',
        dirty_dust: '',
        crushed: '',
        nugget: 'kubejs:titanium_nugget',
        dust: '',
        ingot: 'kubejs:titanium_ingot',
        block: 'kubejs:titanium_block',
        slab: '',
        plate: '',
        rod: '',
        sheet: '',
        slab_sheet: '',
        half_slab_sheet: '',
        melting_temp: 1668
    }
};

const ALLOYS = {
	brass: {
		metalA: ['copper', 2],
		metalB: ['zinc', 1],
		nugget: 'create:brass_nugget',
        dust: '',
        ingot: 'create:brass_ingot',
        block: 'create:brass_block',
        slab: '',
        plate: '',
        rod: '',
        sheet: '',
        slab_sheet: '',
        half_slab_sheet: '',
        melting_temp: 930
	},
    bronze: {
        metalA: ['copper', 9],
        metalB: ['tin', 1],
        nugget: 'kubejs:bronze_nugget',
        dust: '',
        ingot: 'kubejs:bronze_ingot',
        block: 'kubejs:bronze_block',
        slab: '',
        plate: '',
        rod: '',
        sheet: '',
        slab_sheet: '',
        half_slab_sheet: '',
        melting_temp: 950
    },
	constantan: {
		metalA: ['copper', 1],
		metalB: ['nickel', 1],
		nugget: 'immersiveengineering:nugget_constantan',
        dust: 'immersiveengineering:dust_constantan',
        ingot: 'immersiveengineering:ingot_constantan',
        block: 'immersiveengineering:storage_constantan',
        slab: '',
        plate: '',
        rod: '',
        sheet: '',
        slab_sheet: '',
        half_slab_sheet: '',
        melting_temp: 1210
	},
	electrum: {
		metalA: ['gold', 1],
		metalB: ['silver', 1],
		nugget: 'immersiveengineering:nugget_electrum',
        dust: 'immersiveengineering:dust_electrum',
        ingot: 'immersiveengineering:ingot_electrum',
        block: 'immersiveengineering:storage_electrum',
        slab: '',
        plate: '',
        rod: '',
        sheet: '',
        slab_sheet: '',
        half_slab_sheet: '',
        melting_temp: 1064
	}
};
