#For the removal of unwanted post variants.
#Simply set any of them to "false" to "remove", ez..
#You will need to restart the game however if you change anything while the game is running!
#
iron = true
gold = false
copper = false
lead = false
silver = false
nickel = false
constantan = false
electrum = false
uranium = false
nether = false
concrete = true
concreteleaded = true

